server:
  port: 8082
spring:
  application:
    name: api-creditos
eureka:
  client:
    registry-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
  instance:
    hostname: localhost


